-- Démarre une transaction
BEGIN;

-- Supprimer les tables existantes avec CASCADE pour gérer les dépendances
DROP TABLE IF EXISTS "product_variant_attributes", "product_variants", "attribute_values", "attributes", "products", "categories" CASCADE;

-- Table `categories` pour gérer les catégories et sous-catégories
CREATE TABLE IF NOT EXISTS "categories" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "parent_id" INTEGER REFERENCES "categories"("id") ON DELETE CASCADE
);

-- Table `products` pour stocker les informations de base sur les produits
CREATE TABLE IF NOT EXISTS "products" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "base_price" DECIMAL(10, 2) NOT NULL,
    "category_id" INTEGER REFERENCES "categories"("id") ON DELETE SET NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);

-- Table `attributes` pour stocker les types d’attributs (ex. "taille", "couleur")
CREATE TABLE IF NOT EXISTS "attributes" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE
);

-- Table `attribute_values` pour stocker les valeurs possibles pour chaque attribut (ex. "Rouge", "38")
CREATE TABLE IF NOT EXISTS "attribute_values" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "attribute_id" INTEGER REFERENCES "attributes"("id") ON DELETE CASCADE,
    "value" TEXT NOT NULL
);

-- Table `product_variants` pour gérer chaque combinaison unique d’attributs pour un produit
CREATE TABLE IF NOT EXISTS "product_variants" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" INTEGER REFERENCES "products"("id") ON DELETE CASCADE,
    "price" DECIMAL(10, 2) NOT NULL,
    "stock" INTEGER NOT NULL DEFAULT 0
);

-- Table `product_variant_attributes` pour associer chaque variante de produit à des valeurs d’attributs spécifiques
CREATE TABLE IF NOT EXISTS "product_variant_attributes" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "variant_id" INTEGER REFERENCES "product_variants"("id") ON DELETE CASCADE,
    "attribute_value_id" INTEGER REFERENCES "attribute_values"("id") ON DELETE CASCADE,
    UNIQUE ("variant_id", "attribute_value_id")
);


-- Valider les changements en terminant la transaction
COMMIT;
